"""The standard report: plots with explanation, in one self-contained HTML file.

    plumes2.report.build_report(results, "report.html")

This is the last piece of PLAN.md Phase 6 track B, and the requirement it answers is worth quoting
in full, because it is what the design is measured against:

> A standard report: plots **with explanation** -- not a figure dump; each panel says what it
> shows and what to read from it. Main outputs in 3-D space relative to the diffuser. A
> combination of 2-D and 3-D. Centreline, edges, and the spatial gradient. Units independent of
> the solver. Several configurations on one set of axes.

and the instruction governing all of it:

> It is always easy down the road to add more plotting features; what's important at this stage is
> for the data to be **organised, accessible, and traceable**.

Which is why the report is built out of layers that already existed rather than reaching into
`Results`: `plotframe` for a neutral frame (so an exe `.dat` works too), `display` for units (so
the solver stays SI), `comparison` for a derived legend (so nobody hand-types one), `crossplume`
for the profile. This module contributes the panels, the prose, and the page.

⚠️ **Traceability applies to figures too.** Every report carries the code version, the UTC stamp
and the case digest that produced it -- the same provenance a CSV gets. A figure that leaves the
repo without them is not evidence of anything, and a report built from an exe `.dat` says so
plainly, because a `.dat` carries no provenance at all.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from plumes2 import __version__
from plumes2.comparison import Comparison
from plumes2.display import SI, SYSTEMS, UnitSystem
from plumes2.plotframe import PlotFrame, from_dat, from_results
from plumes2.report.page import Header, render_page
from plumes2.report.panels import Panel, build_overlay_panels, build_panels
from plumes2.results import Results

__all__ = [
    "Header",
    "Panel",
    "build_comparison_report",
    "build_panels",
    "build_report",
    "render_comparison",
    "render_report",
    "report_from_dat",
]

_FOOTER = (
    "Generated by plumes2, a Python re-implementation of PLUMES2.0 (UM3 near field, Brooks far "
    "field). Figures are drawn from the same values as the CSVs beside them; the CSVs carry full "
    "precision and this page rounds for reading."
)


def _kpis(
    plot: PlotFrame, units: UnitSystem, farfield: pd.DataFrame | None
) -> tuple[tuple[str, str, str], ...]:
    """The headline numbers, as stat tiles.

    A stat tile rather than a chart, because each of these is a single value and a one-bar bar
    chart is the classic way to miss that.
    """
    frame = plot.frame
    last = frame.iloc[-1]
    length = units.length
    tiles: list[tuple[str, str, str]] = [
        ("Near-field dilution", f"{float(last['dilution']):,.0f}", ""),
    ]
    if "centreline_dilution" in frame.columns:
        tiles.append(("On the centreline", f"{float(last['centreline_dilution']):,.0f}", ""))
    tiles.append(("Trapping depth", f"{length(float(last['depth_m'])):,.1f}", length.label))
    tiles.append(
        ("Plume diameter", f"{length(float(last['plume_diameter_m'])):,.1f}", length.label)
    )
    if "ph_total" in frame.columns:
        tiles.append(("pH at the end", f"{float(last['ph_total']):.2f}", ""))
    if "omega_brucite" in frame.columns:
        tiles.append(("Peak brucite", f"{float(frame['omega_brucite'].max()):,.3g}", ""))
    if farfield is not None and len(farfield):
        tiles.append(
            (
                f"Dilution at {length(float(farfield['distance_m'].iloc[-1])):,.0f}"
                f" {length.label}",
                f"{float(farfield['dilution'].iloc[-1]):,.0f}",
                "",
            )
        )
    return tuple(tiles)


def _header(
    plot: PlotFrame,
    units: UnitSystem,
    farfield: pd.DataFrame | None,
    *,
    title: str | None,
    termination: str | None,
) -> Header:
    case = plot.case
    description = (case.description.strip() if case else "") or "an unnamed case"
    if plot.origin == "dat":
        subtitle = (
            f"Built from output written by the original PLUMES2.0 executable, for {description}. "
            "The secondary quantities were re-derived here; see the notes below."
        )
        # A `.dat` carries no version, stamp or digest of its own, so the only honest provenance
        # is which code read which file. Saying so is the point -- see `plotframe`.
        stamp = (
            f"plumes2 {__version__} reading {plot.source} \N{BULLET} the source file carries no "
            f"provenance of its own \N{BULLET} units: {units.name}"
        )
    else:
        ending = f" The near field ended on {termination}." if termination else ""
        subtitle = f"A near-field and far-field run of {description}.{ending}"
        # `PlotFrame.source` from a run is already the full provenance string: version, input,
        # UTC stamp, case digest and commit. Prefixing the version again would just repeat it.
        stamp = f"{plot.source} \N{BULLET} units: {units.name}"

    return Header(
        title=title or f"Plume report \N{EN DASH} {description}",
        subtitle=subtitle,
        stamp=stamp,
        kpis=_kpis(plot, units, farfield),
        caveats=plot.caveats,
    )


def render_report(
    source: Results | PlotFrame,
    *,
    units: UnitSystem | str = SI,
    title: str | None = None,
    farfield: pd.DataFrame | None = None,
) -> str:
    """The report as an HTML string, for a caller who wants to write it somewhere else.

    `source` is a completed run or an already-adapted `PlotFrame` -- the second is how an exe
    `.dat` gets in, via `plotframe.from_dat`. A run brings its far field along automatically; a
    `PlotFrame` has none to bring, so pass one if you have it.
    """
    resolved = SYSTEMS[units] if isinstance(units, str) else units
    termination: str | None = None
    if isinstance(source, Results):
        plot, farfield, termination = from_results(source), source.farfield, source.termination
    else:
        plot = source

    panels = build_panels(plot, units=resolved, farfield=farfield)
    if not panels:
        raise ValueError(
            f"nothing to report: {plot.source} carries none of the columns any panel needs "
            "(a trajectory needs at least dilution and a position)"
        )
    header = _header(plot, resolved, farfield, title=title, termination=termination)
    return render_page(header, panels, footer=_FOOTER)


def build_report(
    source: Results | PlotFrame,
    path: str | Path,
    *,
    units: UnitSystem | str = SI,
    title: str | None = None,
    farfield: pd.DataFrame | None = None,
) -> Path:
    """Write the report to `path` and return it.

    UTF-8, because the prose and the axis labels carry degree signs and Greek -- unlike the CLI,
    which is held to ASCII for cp1252 consoles. An HTML file declares its own encoding, so it
    travels.
    """
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        render_report(source, units=units, title=title, farfield=farfield), encoding="utf-8"
    )
    return target


def render_comparison(
    comparison: Comparison,
    *,
    units: UnitSystem | str = SI,
    title: str | None = None,
) -> str:
    """Several configurations on one set of axes, as an HTML string.

    The legend is **derived**: `Comparison.labels()` diffs the resolved cases and names what
    actually differs, so nobody types a legend and nobody can mistype one. Which is the whole
    argument for a comparison being a collection of runs rather than a plotting argument.

    Refuses two things rather than fudging them:

    * **More runs than the palette has slots** -- generating a hue is the one thing the data-viz
      standard forbids outright, because a generated colour is indistinguishable from an existing
      one under colour-vision deficiency. See `panels.TooManyRunsError`.
    * **A comparison of identical cases** -- `labels()` returns "identical" for every run, and a
      figure of one line drawn four times in four colours is worse than an error.
    """
    resolved = SYSTEMS[units] if isinstance(units, str) else units
    if not comparison.differences:
        raise ValueError(
            "every case in this comparison is identical, so an overlay would draw the same line "
            "once per colour. Vary something, or report the run on its own."
        )

    labels = comparison.labels()
    frames = [(label, run.nearfield) for label, run in zip(labels, comparison, strict=True)]
    panels = build_overlay_panels(frames, units=resolved)
    if not panels:
        raise ValueError(
            "these runs share no column an overlay can draw; they need at least a position and a "
            "dilution in common"
        )

    stamps = [from_results(run).source for run in comparison]
    differing = ", ".join(sorted({difference.name for difference in comparison.differences}))
    header = Header(
        title=title or f"Plume comparison \N{EN DASH} {len(frames)} configurations",
        subtitle=(
            f"{len(frames)} runs on shared axes, differing in {differing}. Each line ends where "
            "its own run ended; the legend is derived from the cases rather than written."
        ),
        stamp=f"plumes2 {__version__} \N{BULLET} units: {resolved.name} \N{BULLET} "
        + " \N{BULLET} ".join(stamps),
        kpis=tuple(
            (label, f"{float(frame['dilution'].iloc[-1]):,.0f}", "dilution")
            for label, frame in frames
        ),
        caveats=(),
    )
    return render_page(header, panels, footer=_FOOTER)


def build_comparison_report(
    comparison: Comparison,
    path: str | Path,
    *,
    units: UnitSystem | str = SI,
    title: str | None = None,
) -> Path:
    """Write the comparison overlay to `path` and return it."""
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        render_comparison(comparison, units=units, title=title), encoding="utf-8"
    )
    return target


def report_from_dat(
    dat_path: str | Path,
    path: str | Path,
    *,
    case_path: str | Path | None = None,
    units: UnitSystem | str = SI,
    title: str | None = None,
) -> Path:
    """Report an exe `.dat` directly -- the reason the plotting layer is not tied to `Results`.

    Every archived trace, and every run anyone has ever made in the GUI, can be reported this way.
    `case_path` is optional and unlocks the carbonate secondaries the exe never printed: a
    chemistry trace carries TA and DIC but not plume salinity or temperature, so without the case
    those cannot be re-solved. See `plotframe.from_dat`.
    """
    from plumes2.io.dat import read_dat
    from plumes2.io.project import load_project
    from plumes2.io.yaml_case import load_case

    case = None
    if case_path is not None:
        source = Path(case_path)
        case = (
            load_project(source, warn_on_drift=False).to_case()
            if source.suffix.lower() == ".prj"
            else load_case(source)
        )
    dat = read_dat(Path(dat_path))
    plot = from_dat(dat, Path(dat_path), case=case)
    return build_report(
        plot,
        path,
        units=units,
        title=title,
        farfield=None if dat.farfield is None else _farfield_frame(dat.farfield),
    )


def _farfield_frame(table: pd.DataFrame) -> pd.DataFrame | None:
    """The exe's far-field table under our column names, or `None` if it is not recognisable.

    The exe's far-field header varies more than the near-field one does, so this maps what it can
    and declines rather than guessing at a column it does not recognise.
    """
    mapping = {
        "Distnce": "distance_m",
        "Width": "width_m",
        "Dilutn": "dilution",
        "Dilution": "dilution",
    }
    renamed = {
        ours: table[theirs].to_numpy(dtype=float)
        for theirs, ours in mapping.items()
        if theirs in table.columns
    }
    if {"distance_m", "dilution"} - set(renamed):
        return None
    return pd.DataFrame(renamed)
