"""The standard report: plots with explanation, as a PDF or as one self-contained HTML page.

    plumes2.report.build_report(results, "report.pdf")
    plumes2.report.build_report(results, "report.html")

This is the last piece of PLAN.md Phase 6 track B, and the requirement it answers is worth quoting
in full, because it is what the design is measured against:

> A standard report: plots **with explanation** -- not a figure dump; each panel says what it
> shows and what to read from it. Main outputs in 3-D space relative to the diffuser. A
> combination of 2-D and 3-D. Centreline, edges, and the spatial gradient. Units independent of
> the solver. Several configurations on one set of axes.

and the instruction governing all of it:

> It is always easy down the road to add more plotting features; what's important at this stage is
> for the data to be **organised, accessible, and traceable**.

Which is why the report is built out of layers that already existed rather than reaching into
`Results`: `plotframe` for a neutral frame (so an exe `.dat` works too), `display` for units (so
the solver stays SI), `comparison` for a derived legend (so nobody hand-types one), `crossplume`
for the profile. This package contributes the panels, the prose, and two renderings of the same
document: `pdf` for the file that goes into a permit folder, `page` for a browser tab. **The
format follows the path's suffix** -- `.pdf` or `.html` -- and the PDF is the default the CLI
writes.

⚠️ **Traceability applies to figures too.** Every report carries the code version, the UTC stamp
and the case digest that produced it -- the same provenance a CSV gets. A figure that leaves the
repo without them is not evidence of anything, and a report built from an exe `.dat` says so
plainly, because a `.dat` carries no provenance at all.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import replace
from pathlib import Path

import pandas as pd

from plumes2 import __version__
from plumes2.comparison import Comparison
from plumes2.config import Case
from plumes2.display import SI, SYSTEMS, UnitSystem
from plumes2.plotframe import PlotFrame, from_dat, from_results
from plumes2.report.chemistry_gradient import write_chemistry_gradient_figures
from plumes2.report.page import Header, render_page
from plumes2.report.panels import Panel, build_overlay_panels, build_panels
from plumes2.report.pdf import render_pdf
from plumes2.results import Results

__all__ = [
    "Header",
    "Panel",
    "build_combined_report",
    "build_comparison_report",
    "build_panels",
    "build_report",
    "render_comparison",
    "render_report",
    "report_from_dat",
    "write_chemistry_gradient_figures",
    "write_document",
]

_FOOTER = (
    "Generated by plumes2, a Python re-implementation of PLUMES2.0 (UM3 near field, Brooks far "
    "field). Figures are drawn from the same values as the CSVs beside them; the CSVs carry full "
    "precision and this report rounds for reading."
)

#: Suffixes `write_document` knows how to write, and what each means.
_FORMATS = {".pdf": "PDF", ".html": "HTML", ".htm": "HTML"}


def write_document(header: Header, panels: list[Panel], path: str | Path, *, footer: str) -> Path:
    """Write a header and its panels to `path` in the format the suffix names, and return it.

    `.pdf` goes through `report.pdf`, `.html` (or `.htm`) through `report.page`. Anything else is
    refused rather than guessed: a report silently written as HTML under a `.docx` name would be
    opened by the wrong program and blamed on the wrong code.
    """
    target = Path(path)
    kind = _FORMATS.get(target.suffix.lower())
    if kind is None:
        raise ValueError(
            f"cannot write {target.name!r}: a report is a .pdf or a .html file, chosen by the "
            "suffix of the path"
        )
    if kind == "PDF":
        return render_pdf(header, panels, target, footer=footer)
    target.parent.mkdir(parents=True, exist_ok=True)
    # UTF-8, because the prose and the axis labels carry degree signs and Greek -- unlike the CLI,
    # which is held to ASCII for cp1252 consoles. An HTML file declares its own encoding, so it
    # travels.
    target.write_text(render_page(header, panels, footer=footer), encoding="utf-8")
    return target


def _kpis(
    plot: PlotFrame, units: UnitSystem, farfield: pd.DataFrame | None
) -> tuple[tuple[str, str, str], ...]:
    """The headline numbers, as stat tiles.

    A stat tile rather than a chart, because each of these is a single value and a one-bar bar
    chart is the classic way to miss that.
    """
    frame = plot.frame
    last = frame.iloc[-1]
    length = units.length
    tiles: list[tuple[str, str, str]] = []
    if plot.case is not None:
        # The outfall flow, in the unit an operator sets a pump by. Total across the ports.
        tiles.append(("Outfall flow", f"{plot.case.effluent.flow * 60_000.0:,.1f}", "L/min"))
    tiles.append(("Near-field dilution", f"{float(last['dilution']):,.0f}", ""))
    if "centreline_dilution" in frame.columns:
        tiles.append(("On the centreline", f"{float(last['centreline_dilution']):,.0f}", ""))
    tiles.append(("Trapping depth", f"{length(float(last['depth_m'])):,.1f}", length.label))
    tiles.append(
        ("Plume diameter", f"{length(float(last['plume_diameter_m'])):,.1f}", length.label)
    )
    if "ph_total" in frame.columns:
        tiles.append(("pH at the end", f"{float(last['ph_total']):.2f}", ""))
    if "omega_brucite" in frame.columns:
        tiles.append(("Peak brucite", f"{float(frame['omega_brucite'].max()):,.3g}", ""))
    if "omega_brucite_phreeqc" in frame.columns:
        tiles.append(
            ("Peak brucite (PHREEQC)", f"{float(frame['omega_brucite_phreeqc'].max()):,.3g}", "")
        )
    if farfield is not None and len(farfield):
        tiles.append(
            (
                f"Dilution at {length(float(farfield['distance_m'].iloc[-1])):,.0f} {length.label}",
                f"{float(farfield['dilution'].iloc[-1]):,.0f}",
                "",
            )
        )
    return tuple(tiles)


def _header(
    plot: PlotFrame,
    units: UnitSystem,
    farfield: pd.DataFrame | None,
    *,
    title: str | None,
    termination: str | None,
) -> Header:
    case = plot.case
    description = (case.description.strip() if case else "") or "an unnamed case"
    if plot.origin == "dat":
        subtitle = (
            f"Built from output written by the original PLUMES2.0 executable, for {description}. "
            "The secondary quantities were re-derived here; see the notes below."
        )
        # A `.dat` carries no version, stamp or digest of its own, so the only honest provenance
        # is which code read which file. Saying so is the point -- see `plotframe`.
        stamp = (
            f"plumes2 {__version__} reading {plot.source} \N{BULLET} the source file carries no "
            f"provenance of its own \N{BULLET} units: {units.name}"
        )
    else:
        ending = f" The near field ended on {termination}." if termination else ""
        subtitle = f"A near-field and far-field run of {description}.{ending}"
        # `PlotFrame.source` from a run is already the full provenance string: version, input,
        # UTC stamp, case digest and commit. Prefixing the version again would just repeat it.
        stamp = f"{plot.source} \N{BULLET} units: {units.name}"

    return Header(
        title=title or f"Plume report \N{EN DASH} {description}",
        subtitle=subtitle,
        stamp=stamp,
        kpis=_kpis(plot, units, farfield),
        caveats=plot.caveats,
    )


def _document(
    source: Results | PlotFrame,
    *,
    units: UnitSystem | str,
    title: str | None,
    farfield: pd.DataFrame | None,
) -> tuple[Header, list[Panel]]:
    """The report's header and panels -- everything but the format."""
    resolved = SYSTEMS[units] if isinstance(units, str) else units
    termination: str | None = None
    if isinstance(source, Results):
        plot, farfield, termination = from_results(source), source.farfield, source.termination
    else:
        plot = source

    panels = build_panels(plot, units=resolved, farfield=farfield)
    if not panels:
        raise ValueError(
            f"nothing to report: {plot.source} carries none of the columns any panel needs "
            "(a trajectory needs at least dilution and a position)"
        )
    header = _header(plot, resolved, farfield, title=title, termination=termination)
    return header, panels


def render_report(
    source: Results | PlotFrame,
    *,
    units: UnitSystem | str = SI,
    title: str | None = None,
    farfield: pd.DataFrame | None = None,
) -> str:
    """The report as an HTML string, for a caller who wants to write it somewhere else.

    `source` is a completed run or an already-adapted `PlotFrame` -- the second is how an exe
    `.dat` gets in, via `plotframe.from_dat`. A run brings its far field along automatically; a
    `PlotFrame` has none to bring, so pass one if you have it. For the PDF there is no string
    form; use `build_report` with a `.pdf` path.
    """
    header, panels = _document(source, units=units, title=title, farfield=farfield)
    return render_page(header, panels, footer=_FOOTER)


def build_report(
    source: Results | PlotFrame,
    path: str | Path,
    *,
    units: UnitSystem | str = SI,
    title: str | None = None,
    farfield: pd.DataFrame | None = None,
) -> Path:
    """Write the report to `path` -- a PDF for a `.pdf` path, the HTML page for `.html` -- and
    return it. See `write_document` for the dispatch."""
    header, panels = _document(source, units=units, title=title, farfield=farfield)
    return write_document(header, panels, path, footer=_FOOTER)


def _comparison_document(
    comparison: Comparison, *, units: UnitSystem | str, title: str | None
) -> tuple[Header, list[Panel]]:
    resolved = SYSTEMS[units] if isinstance(units, str) else units
    if not comparison.differences:
        raise ValueError(
            "every case in this comparison is identical, so an overlay would draw the same line "
            "once per colour. Vary something, or report the run on its own."
        )

    labels = comparison.labels()
    frames = [(label, run.nearfield) for label, run in zip(labels, comparison, strict=True)]
    panels = build_overlay_panels(frames, units=resolved)
    if not panels:
        raise ValueError(
            "these runs share no column an overlay can draw; they need at least a position and a "
            "dilution in common"
        )

    stamps = [from_results(run).source for run in comparison]
    differing = ", ".join(sorted({difference.name for difference in comparison.differences}))
    flow_sentence, flow_tiles = _flow_note(labels, comparison.cases)
    header = Header(
        title=title or f"Plume comparison \N{EN DASH} {len(frames)} configurations",
        subtitle=(
            f"{len(frames)} runs on shared axes, differing in {differing}. Each line ends where "
            "its own run ended; the legend is derived from the cases rather than written."
            + flow_sentence
        ),
        stamp=f"plumes2 {__version__} \N{BULLET} units: {resolved.name} \N{BULLET} "
        + " \N{BULLET} ".join(stamps),
        kpis=flow_tiles
        + tuple(
            (label, f"{float(frame['dilution'].iloc[-1]):,.0f}", "dilution")
            for label, frame in frames
        ),
        caveats=(),
    )
    return header, panels


def _flow_note(
    labels: tuple[str, ...], cases: tuple[Case, ...]
) -> tuple[str, tuple[tuple[str, str, str], ...]]:
    """The outfall flow, in L/min, for the comparison header: one sentence and one tile per flow.

    An operator sets a pump in litres per minute, and a comparison that leaves the flow implicit
    invites the question. Shared by every run it is stated once, with the port count; differing,
    it is stated per run and becomes what the legend should have said first.
    """
    flows = [case.effluent.flow for case in cases]
    if len({round(flow, 12) for flow in flows}) == 1:
        ports = {case.diffuser.n_ports for case in cases}
        through = f" through {ports.pop()} ports" if len(ports) == 1 else ""
        sentence = (
            f" Outfall flow {flows[0] * 60_000.0:,.1f} L/min "
            f"({flows[0]:.3g} m\N{SUPERSCRIPT THREE}/s)"
            f"{through}, the same in every run."
        )
        return sentence, (("Outfall flow", f"{flows[0] * 60_000.0:,.1f}", "L/min"),)
    listed = "; ".join(
        f"{label}: {flow * 60_000.0:,.1f} L/min" for label, flow in zip(labels, flows, strict=True)
    )
    return f" Outfall flows differ -- {listed}.", tuple(
        (f"Flow, {label}", f"{flow * 60_000.0:,.1f}", "L/min")
        for label, flow in zip(labels, flows, strict=True)
    )


def render_comparison(
    comparison: Comparison,
    *,
    units: UnitSystem | str = SI,
    title: str | None = None,
) -> str:
    """Several configurations on one set of axes, as an HTML string.

    The legend is **derived**: `Comparison.labels()` diffs the resolved cases and names what
    actually differs, so nobody types a legend and nobody can mistype one. Which is the whole
    argument for a comparison being a collection of runs rather than a plotting argument.

    Refuses two things rather than fudging them:

    * **More runs than the palette has slots** -- generating a hue is the one thing the data-viz
      standard forbids outright, because a generated colour is indistinguishable from an existing
      one under colour-vision deficiency. See `panels.TooManyRunsError`.
    * **A comparison of identical cases** -- `labels()` returns "identical" for every run, and a
      figure of one line drawn four times in four colours is worse than an error.
    """
    header, panels = _comparison_document(comparison, units=units, title=title)
    return render_page(header, panels, footer=_FOOTER)


def build_comparison_report(
    comparison: Comparison,
    path: str | Path,
    *,
    units: UnitSystem | str = SI,
    title: str | None = None,
) -> Path:
    """Write the comparison overlay to `path` -- PDF or HTML by suffix -- and return it."""
    header, panels = _comparison_document(comparison, units=units, title=title)
    return write_document(header, panels, path, footer=_FOOTER)


def build_combined_report(
    comparison: Comparison,
    path: str | Path,
    *,
    units: UnitSystem | str = SI,
    title: str | None = None,
    names: Sequence[str] | None = None,
    sections: Sequence[tuple[str, Results]] | None = None,
) -> Path:
    """One file for a multi-run study: the comparison overlays, then every run's full report.

    The overlays come first, exactly as `build_comparison_report` draws them, with the derived
    legend and the outfall flow in the header. Each run's own panels follow as sections whose
    titles carry the run's name, so the plume in space, the side view, the chemistry gradients
    and the far field of every configuration are in the same document as the comparison.
    Asked for on 2026-09-08, after a study wrote a PDF per effluent plus a separate overlay.

    `names` are the section headings, one per run, in the comparison's order -- the study's own
    words for its cases ("seawater dosed to pH 9.8"). They are headings, not the legend: the
    legend stays derived from the cases, as it must. Without `names` the derived labels serve.

    `sections` replaces the default sections -- the comparison's own runs under `names` -- with
    an explicit `(heading, run)` list. For when the document should carry more runs than the
    overlays can (the palette has four slots): four effluents overlaid on the acute ambient,
    then eight sections, each effluent on the acute and on the chronic profile.
    """
    resolved = SYSTEMS[units] if isinstance(units, str) else units
    header, panels = _comparison_document(comparison, units=resolved, title=title)
    headings = tuple(names) if names is not None else comparison.labels()
    if len(headings) != len(comparison):
        raise ValueError(
            f"{len(headings)} names for {len(comparison)} runs -- one heading per run, in order"
        )
    combined = list(panels)
    listed_sections = (
        list(sections) if sections is not None else list(zip(headings, comparison, strict=True))
    )
    for index, (name, run) in enumerate(listed_sections, start=1):
        _, own = _document(run, units=resolved, title=None, farfield=None)
        combined.extend(
            replace(
                panel, key=f"run-{index}-{panel.key}", title=f"{name} \N{EM DASH} {panel.title}"
            )
            for panel in own
        )
    listed = "; ".join(name for name, _ in listed_sections)
    # The stat tiles name the runs by their headings too: a derived label is a legend entry, and
    # as a tile title it overflows the tile.
    flow_tiles = tuple(tile for tile in header.kpis if tile[2] == "L/min")
    run_tiles = tuple(
        (name, f"{float(run.nearfield['dilution'].iloc[-1]):,.0f}", "dilution")
        for name, run in zip(headings, comparison, strict=True)
    )
    header = replace(
        header,
        subtitle=header.subtitle
        + f" The overlays are followed by the full report of each run: {listed}.",
        kpis=flow_tiles + run_tiles,
    )
    return write_document(header, combined, path, footer=_FOOTER)


def report_from_dat(
    dat_path: str | Path,
    path: str | Path,
    *,
    case_path: str | Path | None = None,
    units: UnitSystem | str = SI,
    title: str | None = None,
) -> Path:
    """Report an exe `.dat` directly -- the reason the plotting layer is not tied to `Results`.

    Every archived trace, and every run anyone has ever made in the GUI, can be reported this way.
    `case_path` is optional and unlocks the carbonate secondaries the exe never printed: a
    chemistry trace carries TA and DIC but not plume salinity or temperature, so without the case
    those cannot be re-solved. See `plotframe.from_dat`.
    """
    from plumes2.io.dat import read_dat
    from plumes2.io.project import load_project
    from plumes2.io.yaml_case import load_case

    case = None
    if case_path is not None:
        source = Path(case_path)
        case = (
            load_project(source, warn_on_drift=False).to_case()
            if source.suffix.lower() == ".prj"
            else load_case(source)
        )
    dat = read_dat(Path(dat_path))
    plot = from_dat(dat, Path(dat_path), case=case)
    return build_report(
        plot,
        path,
        units=units,
        title=title,
        farfield=None if dat.farfield is None else _farfield_frame(dat.farfield),
    )


def _farfield_frame(table: pd.DataFrame) -> pd.DataFrame | None:
    """The exe's far-field table under our column names, or `None` if it is not recognisable.

    The exe's far-field header varies more than the near-field one does, so this maps what it can
    and declines rather than guessing at a column it does not recognise.
    """
    mapping = {
        "Distnce": "distance_m",
        "Width": "width_m",
        "Dilutn": "dilution",
        "Dilution": "dilution",
    }
    renamed = {
        ours: table[theirs].to_numpy(dtype=float)
        for theirs, ours in mapping.items()
        if theirs in table.columns
    }
    if {"distance_m", "dilution"} - set(renamed):
        return None
    return pd.DataFrame(renamed)
